### PR TITLE
Fixed rendering issues with detailed polylines

### PR DESCRIPTION
**Pull request by Sijmen**
Added the simplify step before offsetting the actual point. This reduces the number of points in the line and smooths it. The end result is unaffected in simple polylines and is significantly improved on detailed polylines.

This should fix issues as seen in #1

### CODE REVIEW

**Comment by LekisS** [comment]
Works great on my end, thanks

**Comment by KirillMetrik** [comment]
@bbecquet could you please merge this? Would really like to reuse this fix as a part of PolylineOffset release.

**Comment by BenSuskins** [comment]
@bbecquet could you please merge this? Would be really great to have this

**Comment by bbecquet** [comment]
Sorry I know it's a bit ridiculous to merge this PR sooo late… I haven't maitained this plugin at all for 3 years, and now I hope to find time to rewrite it from scratch, as I think there are fundamental design flaws that cause most of the problems.
But this fixes a lot of rendering issues, so it may be useful to some users in the meantime, even if they probably use their own fork.

**Pull request merged**
